package io.legado.app.constant

object PreferKey {
    const val versionCode = "versionCode"
    const val language = "language"
    const val themeMode = "themeMode"
    const val hideStatusBar = "hideStatusBar"
    const val clickTurnPage = "clickTurnPage"
    const val clickAllNext = "clickAllNext"
    const val hideNavigationBar = "hideNavigationBar"
    const val precisionSearch = "precisionSearch"
    const val speakEngine = "speakEngine"
    const val readAloudByPage = "readAloudByPage"
    const val ttsSpeechRate = "ttsSpeechRate"
    const val prevKey = "prevKeyCode"
    const val nextKey = "nextKeyCode"
    const val showRss = "showRss"
    const val bookshelfLayout = "bookshelfLayout"
    const val bookshelfSort = "bookshelfSort"
    const val recordLog = "recordLog"
    const val processText = "process_text"
    const val cleanCache = "cleanCache"
    const val saveTabPosition = "saveTabPosition"
    const val pageAnim = "pageAnim"
    const val fontFolder = "fontFolder"
    const val backupPath = "backupUri"
    const val restoreIgnore = "restoreIgnore"
    const val threadCount = "threadCount"
    const val webPort = "webPort"
    const val keepLight = "keep_light"
    const val webService = "webService"
    const val webDavUrl = "web_dav_url"
    const val webDavAccount = "web_dav_account"
    const val webDavPassword = "web_dav_password"
    const val webDavCreateDir = "webDavCreateDir"
    const val changeSourceLoadToc = "changeSourceLoadToc"
    const val chineseConverterType = "chineseConverterType"
    const val launcherIcon = "launcherIcon"
    const val textSelectAble = "selectText"
    const val lastBackup = "lastBackup"
    const val bodyIndent = "textIndent"
    const val shareLayout = "shareLayout"
    const val readStyleSelect = "readStyleSelect"
    const val systemTypefaces = "system_typefaces"
    const val readBodyToLh = "readBodyToLh"
    const val textFullJustify = "textFullJustify"
    const val textBottomJustify = "textBottomJustify"
    const val autoReadSpeed = "autoReadSpeed"
    const val barElevation = "barElevation"
    const val transparentStatusBar = "transparentStatusBar"
    const val defaultCover = "defaultCover"
    const val replaceEnableDefault = "replaceEnableDefault"
    const val showBrightnessView = "showBrightnessView"

    const val cPrimary = "colorPrimary"
    const val cAccent = "colorAccent"
    const val cBackground = "colorBackground"
    const val cBBackground = "colorBottomBackground"

    const val cNPrimary = "colorPrimaryNight"
    const val cNAccent = "colorAccentNight"
    const val cNBackground = "colorBackgroundNight"
    const val cNBBackground = "colorBottomBackgroundNight"

    // AI settings
    const val aiBaseUrl = "ai_base_url"
    const val aiApiKey = "ai_api_key"
    const val aiModel = "ai_model"
    const val aiProvider = "ai_provider"
    const val aiStream = "ai_stream"
    const val aiTimeout = "ai_timeout"
    const val aiMaxRounds = "ai_max_rounds"
    const val aiSessionWindow = "ai_session_window"

    // AI 聊天背景自定义（RikkaHub 风格：图片+不透明度 / 极光渐变）
    const val aiChatBgPath = "ai_chat_bg_path"
    const val aiChatBgOpacity = "ai_chat_bg_opacity"
    const val aiChatBgGradient = "ai_chat_bg_gradient"
}